### ISSUE TITLE
ss无法配置appid

### ISSUE THREAD

**Issue by HJH12315** [jzp820927/Deploy_XXNET_Server#4]
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "D:\XX-Net-3.6.2\Deploy_XXNET_Server-master\uploader.py", line 141, in <module>
    main()
  File "D:\XX-Net-3.6.2\Deploy_XXNET_Server-master\uploader.py", line 127, in main
    upload('gae', appid)
  File "D:\XX-Net-3.6.2\Deploy_XXNET_Server-master\uploader.py", line 111, in upload
    appcfg.main(['appcfg', 'rollback', dirname])
  File "D:\XX-Net-3.6.2\Deploy_XXNET_Server-master\google_appengine\google\appengine\tools\appcfg.py", line 5388, in main
    result = AppCfgApp(argv).Run()
  File "D:\XX-Net-3.6.2\Deploy_XXNET_Server-master\google_appengine\google\appengine\tools\appcfg.py", line 2951, in Run
    self.action(self)
  File "D:\XX-Net-3.6.2\Deploy_XXNET_Server-master\google_appengine\google\appengine\tools\appcfg.py", line 5044, in __call__
    return method()
  File "D:\XX-Net-3.6.2\Deploy_XXNET_Server-master\google_appengine\google\appengine\tools\appcfg.py", line 4397, in Rollback
    self._Rollback()
  File "D:\XX-Net-3.6.2\Deploy_XXNET_Server-master\google_appengine\google\appengine\tools\appcfg.py", line 4442, in _Rollback
    appversion.Rollback(force_rollback)
  File "D:\XX-Net-3.6.2\Deploy_XXNET_Server-master\google_appengine\google\appengine\tools\appcfg.py", line 2362, in Rollback
    force_rollback='1' if force_rollback else '0')
  File "D:\XX-Net-3.6.2\Deploy_XXNET_Server-master\google_appengine\google\appengine\tools\appcfg.py", line 1696, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 247, in Send
    url, method=method, body=payload, headers=headers)
  File "google_appengine\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "google_appengine\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "google_appengine\httplib2\__init__.py", line 1268, in _conn_request
    conn.connect()
  File "google_appengine\httplib2\__init__.py", line 1011, in connect
    sock.connect((self.host, self.port))
  File "PySocks\socks.py", line 740, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:1080: [Errno 10060]
请按任意键继续. . .

**Comment by jzp820927** [comment]
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:1080: [Errno 10060]
估计是你的 $$ 有问题，请你先检查你的 $$ 能正常使用。
